services:
  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=fastapi
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=fastapi

  fastapi_mini_app:
    depends_on:
        - db
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=fastapi
      - DB_PASS=your_password
      - DB_PORT=3306
      - DB_USER=fastapi
    

  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8084:8080"
    depends_on:
      - fastapi_mini_app